name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check fmt
        run: cargo fmt -- --check
      - name: Build
        run: ./ci.sh
